### ISSUE TITLE
Installation Instructions clarification

### ISSUE THREAD

**Issue by mojoa** [zwbetz-gh/cupper-hugo-theme#1]
This may need some clarification. 
Most of the themes use git clone, not sure why your install is different.
https://github.com/gohugoio/hugoThemes#installing-a-single-theme

Installation
From the root of your site:

git submodule add https://github.com/zwbetz-gh/cupper-hugo-theme.git themes/cupper-hugo-theme

Results in:
$ git submodule add https://github.com/zwbetz-gh/cupper-hugo-theme.git themes/cupper-hugo-theme
fatal: not a git repository (or any of the parent directories): .git
$

**Comment by zwbetz-gh** [comment]
Users are free to install the theme however they wish. A regular `git clone` will work just fine. 

I included steps to add it as a git submodule since this is the best way, in my opinion, to install themes when your site will be hosted somewhere like Netlify. 

And you got that error because your site was not initialized as as git repo. You need to run `git init` in your site first, then run the command to add the theme as a submodule.

**Comment by mojoa** [comment]
OK Thanks!
