### ISSUE TITLE
Error rendering figure shortcode

### ISSUE THREAD

**Issue by sumitbirla** [zwbetz-gh/cupper-hugo-theme#12]
I am fairly new to Hugo and still learning how to use it, so this error could be a set up error on my part.  However, I am unable to use the 'figure' shortcode due to the following error:

`{{< figure src="/wp-content/uploads/2007/02/cable_cord.jpg" >}}`

`hugo/themes/cupper-hugo-theme/layouts/shortcodes/figure.html:22:23": execute of template failed: template: shortcodes/figure.html:22:23: executing "shortcodes/figure.html" at <$original.Permalink>: nil pointer evaluating resource.Resource.Permalink`

It appears to be related to permalink.   But I can't really tell what I am missing.  If I delete the `figure.html` from the themes directly and use the default Hugo one, it works fine.

**Comment by zwbetz-gh** [comment]
Hi. So the theme figure shortcode only works for page bundle image resources. For an example usage see https://github.com/zwbetz-gh/cupper-hugo-theme/blob/master/exampleSite/content/post/nasa-images/index.md

**Comment by sumitbirla** [comment]
Got it.   Thanks!

**Comment by Teebusch** [comment]
It seems that Cupper's figure shortcode masks Hugo's [default figure shortcode](https://gohugo.io/content-management/shortcodes/#figure). The two are different enough that they are both useful in different situations:

* Hugo's figure shortcode allows linking of images in `/static` and adding a link to a picture directly
* Cupper's shortcode has image processing built in, which is very useful. However, it centers the figure horizontally and "forces" a caption (otherwise there will be a "Figure x" text under the figure. 

I would suggest to rename Cupper's shortcode, so Hugo's can be accessed.

(correct me if I'm wrong. I am new to Hugo)

**Comment by zwbetz-gh** [comment]
@Teebusch see https://github.com/zwbetz-gh/cupper-hugo-theme/issues/17. I do one issue per GitHub issue to keep things clean.
