### ISSUE TITLE
parameter for logo file

### ISSUE THREAD

**Issue by datatemplar** [zwbetz-gh/cupper-hugo-theme#4]
Hello,

first time I use Hugo and with your theme it is really nice. However to change the logo under static/images/ in your theme don't seem the best practice. Could you prepare a correction so it can be integrate directly in the site config files? 

Thanks

**Comment by zwbetz-gh** [comment]
Hi @datatemplar, I'm glad you like the theme. 

So you actually don't have to replace the theme's logo. You can just place your logo here:

```
your-site/static/images/logo.svg
```

And Hugo will automatically use your logo instead of the theme's logo.

Also, SVG logos are best since their colors will be inverted when the theme is viewed in "dark mode".

**Comment by zwbetz-gh** [comment]
The logo docs have been updated. See 51f3f7b

**Comment by zwbetz-gh** [comment]
Closing this issue
