### ISSUE TITLE
Menu: divider, '-' or hr, and non-linkable links

### ISSUE THREAD

**Issue by joelouthan** [zwbetz-gh/cupper-hugo-theme#49]
Site: [https://theologic.us](https://theologic.us)
Github: [https://github.com/joelouthan/theologic.us](https://github.com/joelouthan/theologic.us)

## Issue

Because I cannot see this in the .css file, I don't know how menu.nav is controlled and displayed.

## Solution Requested

As you can see within my blog, I would like a way to organize my links with:
- non-linkable headers (without the bookmark icon as not to be confusing)
- headers with font weight similar to h1, h2, etc..
- And hr or '-' or horizontal lines

Is it possible to add something like menu.divider or other menu items?  If so, how do you do that?

**Describe alternatives you've considered**
Right now, I am sticking text in under menu.nav because that is the only menu.nav I am aware of. I don't know how to add more different types of menu items other than menu.nav.

**Comment by zwbetz-gh** [comment]
Most users of this theme only have a few menu items. What you're asking for is an edge case. I'm not going to implement it because it would not get much usage. But I can point you in the right direction if you choose to do it yourself. 

## CSS

The nav menu styles are controlled by CSS file https://github.com/zwbetz-gh/cupper-hugo-theme/blob/master/assets/css/template-styles.css

Do a search for `pattern` in that CSS file to find the relevant selectors.

## Hugo Template

This template logic determines whether the bookmark icon is shown https://github.com/zwbetz-gh/cupper-hugo-theme/blob/78021345d9f3bd1f342d87d82333d9718786e327/layouts/partials/nav.html#L17-L22

**Comment by joelouthan** [comment]
@zwbetz-gh definitely no need for implementation. This is exactly what I needed. Thank you.
