### ISSUE TITLE
Disqus comments are disabled.

### ISSUE THREAD

**Issue by jpastorm** [zwbetz-gh/cupper-hugo-theme#70]
I am trying to implement disqus, but no success. I see you don't have it active on their netflify page either
![image](https://user-images.githubusercontent.com/54615061/167594542-dc26ef7b-817d-4cce-a90b-40cae09eb6ef.png)

**Comment by zwbetz-gh** [comment]
I’ve intentionally disabled comments on the demo site. 

When using this theme, comments are automatically disabled when running the local server. See https://github.com/zwbetz-gh/cupper-hugo-theme/blob/master/layouts/partials/disqus.html#L7

Feel free to override that. Otherwise, once you deploy your site, comments will be enabled.

**Comment by zwbetz-gh** [comment]
Here’s an example of how to override a theme file 

https://zwbetz.com/override-a-hugo-theme/
